#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-TipTip
Version  : master
Release  : 1
URL      : https://github.com/drewwilson/TipTip/archive/master.tar.gz
Source0  : https://github.com/drewwilson/TipTip/archive/master.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/com/drewwilson/code/jquery.tipTip/1.3/jquery.tipTip-1.3-minified.js
Source2  : https://repo.gradle.org/gradle/libs-releases/com/drewwilson/code/jquery.tipTip/1.3/jquery.tipTip-1.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0 MIT
Requires: mvn-TipTip-data = %{version}-%{release}

%description
TipTip
http://www.drewwilson.com
http://code.drewwilson.com/entry/tiptip-jquery-plugin

%package data
Summary: data components for the mvn-TipTip package.
Group: Data

%description data
data components for the mvn-TipTip package.


%prep
%setup -q -n TipTip-master

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/drewwilson/code/jquery.tipTip/1.3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/drewwilson/code/jquery.tipTip/1.3/jquery.tipTip-1.3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/drewwilson/code/jquery.tipTip/1.3/jquery.tipTip-1.3.pom
